stages:
    - test

before_script:
    - apk add --no-cache python3 py3-pip
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install coverage pytest pytest-cov
    - pip install -e .

tests:
    stage: test
    script:
        - pytest tests --junitxml=.testreports/report.xml --cov=suppy --cov-report term --cov-report xml:.testreports/coverage.xml --cov-report html:.testreports/html
    artifacts:
        when: always
        reports:
            coverage_report:
                coverage_format: cobertura
                path: .testreports/coverage.xml
            junit: .testreports/report.xml
        paths:
            - .testreports/html
    coverage: '/TOTAL.*? (100(?:\.0+)?%|[1-9]?\d(?:\.\d+)?%)/'
